version: "3.8"

services:
  postgres:
    container_name: discord-analytics-pg
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: gAX78IkIs9HhokQrqUZkYihEkGyCl4NQGMFJ6iVj
      POSTGRES_DB: discord-analytics
    volumes:
      - ./data/postgresql:/bitnami/postgresql

  cache:
    container_name: discord-analytics-cache
    image: bitnami/redis
    environment:
      - REDIS_DATABASE=discord-analytics-cache
      - REDIS_PASSWORD=RyGmwyOXWR1u1N8kz0YjPgbKPnxIFwcpSP1sMywA
    ports:
      - 6379:6379
    volumes:
      - ./data/redis:/data
